import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { MainNav } from '../components/Nav.js'
import { CoursesCard } from '../components/Card'
import { PrimaryButton } from '../components/Button'
import { Footer } from '../components/Footer'

export default function Courses() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainNav />
      <main className={styles.landingpage}>
        <div className={styles.welcome}>
          <div className={styles.welleft}>
            <h1>Learn Crypto</h1>
            <h1>Earn Crypto</h1>
            <h4>Attend live session with top expert and win Crypto rewards for your participation.</h4>
            <PrimaryButton title="Join Now" />
          </div>
          <div style={{ marginTop: '-30px' }} className={styles.welright}>
            <Image 
              // src="/welcome.gif"
              src="/welcome.png"
              alt="Create NFT"
              width={520}
              height={520}
              className="welcomeimg"
              priority
            />
          </div>
        </div>
      </main>
      <div className={styles.coursespage}>
            <div className={styles.coursescards}>
              <CoursesCard />
              <CoursesCard />
              <CoursesCard />
            </div>
          </div>
      <Footer />
    </>
  )
}
